---
name: Pull Requests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'internal/**'
      - 'cmd/**'
      - 'go.mod'
      - 'go.sum'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Cache Golang dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-go-rod
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.event.number }}-${{ hashFiles('go.sum') }}
          path: |
            ~/.cache/rod
            ~/go/pkg/

      - name: Build
        run: |
          go build -v -o kuve ./main.go
          echo "Build completed."

      - name: Test with the Go CLI
        run: go test ./...

      - name: Test with kuve
        run: |
          ./kuve --version
          ./kuve --help
